### ISSUE TITLE
Show More Feature Not Working 

### ISSUE THREAD

**Issue by moinkhan780** [Crazelu/fluttertagger#9]
Show More Feature Not Working

**Comment by Crazelu** [comment]
@moinkhan780 can you describe the issue in detail?
I’m not aware of a “Show More Feature” for this library

**Comment by moinkhan780** [comment]
> @moinkhan780 can you describe the issue in detail? I’m not aware of a “Show More Feature” for this library

When we have large no of text (Long text). In you example you use this feature but it doesn't work.

**Comment by Crazelu** [comment]
@moinkhan780 you have everything in the `CustomText` widget to get that to work.
`onSuffixPressed` which will be called when the "Show More" text is pressed.
`showAllText` which indicates whether the full text should be shown.
`suffix` which is the text (current default is Show More).

What you want to do is maintain a boolean state, which you will pass as the value of `showAllText` to the `CustomText` widget. Then for `onSuffixPressed`, provide a function that toggles the boolean state.

I'm closing this because this is not a feature of FlutterTagger.
